[package]
name = "lucioof/farming-game"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
rodux = "upliftgames/rodux@^3.0.0"
promise = "evaera/promise@^4.0.0"
react = "jsdotlua/react@^17.1.0"
react-roblox = "jsdotlua/react-roblox@^17.1.0"

[dev-dependencies]

[server-dependencies]

[place]
shared-packages = ["Packages"]